---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: create a temporary directory
    tempfile:
      state: directory
    register: tempdir

  - name: copy project to temp dir
    copy:
      src: ../0_spring_application
      dest: "{{ tempdir.path }}"

  - name: make mvnw executable
    file:
      path: "{{ tempdir.path }}/0_spring_application/mvnw"
      mode: '755'

  # The resources directory contains settings for local testing so
  # delete the directory...
  - name: delete the contents of the resources directory
    file:
      path: "{{ tempdir.path }}/0_spring_application/src/main/resources"
      state: absent

  # ...recreate the empty directory...
  - name: recreate resources directory
    file:
      path: "{{ tempdir.path }}/0_spring_application/src/main/resources"
      state: directory

  # ...and populate the directory with the application file used in OCI.
  - name: populate the application.yml file
    template:
      src: ./templates/application.yml
      dest: "{{ tempdir.path }}/0_spring_application/src/main/resources/application.yml"

  - name: package spring application
    shell: cd {{ tempdir.path }}/0_spring_application && ./mvnw -Poci clean package

- hosts: all
  gather_facts: false

  tasks:
  - block:
    - name: copy schema.sql
      copy:
        src: ./templates/schema.sql
        dest: ~/schema.sql

    - name: create schema
      shell: /opt/oracle/sqlcl/bin/sql -cloudconfig /home/opc/{{ project_name }}_wallet.zip -L 'admin/"{{ database_admin_password }}"@{{ project_name }}_low' @/home/opc/schema.sql

    - name: delete schema.sql
      file:
        path: ~/schema.sql
        state: absent
    run_once: True      

  - name: copy jar
    copy:
      src: "{{ hostvars['localhost']['tempdir']['path'] }}/0_spring_application/target/demo-0.0.1-SNAPSHOT.jar"
      dest: ~/demo.jar

  - name: copy service definition
    copy:
      src: templates/demo.service
      dest: /etc/systemd/system
    become: True

  - name: start service
    systemd:
      name: demo.service
      state: started
      enabled: True
    become: True

- hosts: localhost
  gather_facts: false

  tasks:
  - name: delete temporary directory
    file:
      path: "{{ tempdir.path }}"
      state: absent
