---
- hosts: localhost
  gather_facts: false

  tasks:
  # The src/main/resources directory contains settings for local testing
  # wit the H2 database. We'll replace the configuration with OCI settings.
  - name: back up the src/main/resources directory before we replace it
    copy:
      src: ../0_spring_application/src/main/resources
      dest: /tmp/src_main_resources

  - block:
    - name: delete the contents of the resources directory
      file:
        path: ../0_spring_application/src/main/resources
        state: absent

    - name: recreate an empty resources directory
      file:
        path: ../0_spring_application/src/main/resources
        state: directory

    - name: populate the application.yml file
      template:
        src: ./templates/application.yml
        dest: ../0_spring_application/src/main/resources

    # Use the OCI profile so that we build for the Oracle 19c DB
    - name: package spring application
      shell: cd ../0_spring_application && ./mvnw -Poci clean package

    always:
    - name: delete the contents of the resources directory
      file:
        path: ../0_spring_application/src/main/resources
        state: absent

    - name: restore the back up to the resources directory
      copy:
        src: /tmp/src_main_resources/resources
        dest: ../0_spring_application/src/main

    - name: delete the back up
      file:
        path: /tmp/src_main_resources
        state: absent

- hosts: all
  gather_facts: false

  tasks:
  - block:
    - name: copy schema.sql
      copy:
        src: ./templates/schema.sql
        dest: ~/schema.sql

    - name: create schema
      shell: /opt/oracle/sqlcl/bin/sql -cloudconfig /home/opc/{{ project_name }}_wallet.zip -L 'admin/"{{ database_admin_password }}"@{{ project_name }}_low' @/home/opc/schema.sql

    - name: delete schema.sql
      file:
        path: ~/schema.sql
        state: absent
    run_once: True      

  - name: copy jar
    copy:
      src: ../0_spring_application/target/demo-0.0.1-SNAPSHOT.jar
      dest: ~/demo.jar

  - name: copy service definition
    copy:
      src: templates/demo.service
      dest: /etc/systemd/system
    become: True

  - name: start service
    systemd:
      name: demo.service
      state: started
      enabled: True
    become: True

- hosts: localhost
  gather_facts: false

  tasks:
    # Clean up the JAR since it isn't useful locally (and contains secrets)
    - name: delete artifacts
      shell: cd ../0_spring_application && ./mvnw -Poci clean
