server:
  port: {{ webservice_port }}

spring:
  datasource:
    url: jdbc:oracle:thin:@{{ project_name }}_low?TNS_ADMIN=/home/opc/{{ project_name }}_wallet
    username: admin
    password: "{{ database_admin_password }}"

# This provides detailed information about health which can be useful to us.
# Unfortunately it can be useful to hackers as well. If you're going to do this
# you should probably set up a load balancer rewrite rule to rewrite /actuator
# paths to redirect to a "forbiddern" or "not found" page.
management:
  endpoint:
    health:
      show-details: always
