server:
  port: {{ webservice_port }}

spring:
  datasource:
    url: jdbc:oracle:thin:@{{ project_name }}_low?TNS_ADMIN=/home/opc/{{ project_name }}_wallet
    username: admin
    password: "{{ database_admin_password }}"

management:
  endpoint:
    health:
      show-details: always
