---
- hosts: all
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
  - name: open firewall for http
    firewalld:
      port: "{{ webservice_port }}/tcp"
      state: enabled
    become: True

  - name: install java 11
    yum:
      name: java-11-openjdk-devel
      state: latest
    become: True

  - name: install sqlcl
    yum:
      name: sqlcl
      state: latest
    become: True

  - name: copy the wallet
    copy:
      src: ../terraform/database_wallet.zip.asc
      dest: ~/database_wallet.zip.asc

  - name: base64 decode the wallet
    shell: base64 -d ~/database_wallet.zip.asc > ~/database_wallet.zip

  - name: create a directory for the wallet
    file:
      path: ~/database_wallet
      state: directory

  - name: unzip the wallet
    unarchive:
      src: ~/database_wallet.zip
      remote_src: True
      dest: ~/database_wallet

  - name: clean up the base64-encoded wallet file
    file:
      path: ~/database_wallet.zip.asc
      state: absent
