---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: package spring application
    shell: cd ../spring_web_service && ./mvnw clean package

- hosts: all
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
  - name: copy jar
    copy:
      src: ../spring_web_service/target/demo-0.0.1-SNAPSHOT.jar
      dest: ~/demo.jar

  - name: copy service definition
    copy:
      src: templates/demo.service
      dest: /etc/systemd/system
    become: True

  - name: start service
    systemd:
      name: demo.service
      state: started
      enabled: True
    become: True
