---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: back up the application.yml file before we clobber it
    copy:
      src: ../0_spring_application/src/main/resources/application.yml
      dest: /tmp/application.yml

  - block:
    - name: populate the application.yml file
      template:
        src: ./templates/application.yml
        dest: ../0_spring_application/src/main/resources

    - name: package spring application
      shell: cd ../0_spring_application && ./mvnw clean package

    always:
      - name: restore the back up
        copy:
          src: /tmp/application.yml
          dest: ../0_spring_application/src/main/resources/application.yml
      - file:
          path: /tmp/application.yml
          state: absent

- hosts: all
  gather_facts: false

  tasks:
  - block:
    - name: copy schema.sql
      copy:
        src: ./templates/schema.sql
        dest: ~/schema.sql

    - name: create schema
      shell: /opt/oracle/sqlcl/bin/sql -cloudconfig /home/opc/database_wallet.zip -L 'admin/{{ database_admin_password }}@{{ project_name }}_medium' @/home/opc/schema.sql

    - name: delete schema.sql
      file:
        path: ~/schema.sql
        state: absent
    run_once: True      

  - name: copy jar
    copy:
      src: ../0_spring_application/target/demo-0.0.1-SNAPSHOT.jar
      dest: ~/demo.jar

  - name: copy service definition
    copy:
      src: templates/demo.service
      dest: /etc/systemd/system
    become: True

  - name: start service
    systemd:
      name: demo.service
      state: started
      enabled: True
    become: True
