---
- hosts: all
  gather_facts: false

  tasks:
  - name: open firewall for the spring service
    firewalld:
      port: "{{ webservice_port }}/tcp"
      state: enabled
      immediate: True
      permanent: True
    become: True

  - name: install java
    yum:
      name: java-11-openjdk-devel
      state: latest
    become: True

  - name: install sqlcl
    yum:
      name: sqlcl
      state: latest
    become: True

  - name: copy the wallet
    copy:
      src: ../1_provision/{{ project_name }}_wallet.zip.asc
      dest: ~/{{ project_name }}_wallet.zip.asc

  - name: base64 decode the wallet
    shell: base64 -d ~/{{ project_name }}_wallet.zip.asc > ~/{{ project_name }}_wallet.zip

  - name: create a directory for the wallet
    file:
      path: ~/{{ project_name }}_wallet
      state: directory

  - name: unzip the wallet
    unarchive:
      src: ~/{{ project_name }}_wallet.zip
      remote_src: True
      dest: ~/{{ project_name }}_wallet

  - name: clean up the base64-encoded wallet file
    file:
      path: ~/{{ project_name }}_wallet.zip.asc
      state: absent
